// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://testpages.herokuapp.com/styled/basic-html-form-test.html");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("Singh");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("test");
    driver.findElement(By.name("comments")).click();
    driver.findElement(By.name("comments")).sendKeys("my test ");
    driver.findElement(By.name("checkboxes[]")).click();
    driver.findElement(By.name("radioval")).click();
    {
      WebElement dropdown = driver.findElement(By.name("multipleselect[]"));
      dropdown.findElement(By.xpath("//option[. = 'Selection Item 1']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.name("multipleselect[]"));
      dropdown.findElement(By.xpath("//option[. = 'Selection Item 4']")).click();
    }
    driver.findElement(By.name("dropdown")).click();
    {
      WebElement dropdown = driver.findElement(By.name("dropdown"));
      dropdown.findElement(By.xpath("//option[. = 'Drop Down Item 1']")).click();
    }
    driver.findElement(By.cssSelector(".styled-click-button:nth-child(2)")).click();
  }
}
